// data_u3.js — Unit 3: Heroes (Arts & Literature)
window.HR_UNITS = window.HR_UNITS || [];
window.HR_UNITS.push({
  title: "Unit 3: Heroes",
  eq: "What makes a hero?",
  weeks: [
    { w:1, genre:"Historical Fiction", text:"Below Deck: A Titanic Story", author:"by Tony Bradman", wq:"What qualities do we see in heroes?", comp:"Analyze Plot and Setting; Correct or Confirm Predictions", vocab:"Words that Describe Plot and Setting (Related Words)", word:"Prefixes pre-, dis-, in-, im-, non-", craft:"Explain & Use Illustrations", belowRes:"Foldable Decodable: \"Mato Helps\" | myFocus Reader: \"A Hero for Animals\"",
      below:{ id:"U3W1-B", skill:"Plot & setting; prefixes (pre-, dis-, in-, im-, non-)", fp:"J-K", lex:"BR-330L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Mato Helps\", myView myFocus Reader \"A Hero for Animals\", prefix flip cards", proc:["Review 2 prefixes and their meanings with picture cues (non- = not).","Echo-read \"Mato Helps,\" building prefix words together.","Read myFocus Reader \"A Hero for Animals\" in chunks.","After each chunk, ask 'Where is this happening?' using a picture-choice prompt.","Predict what might happen next using a sentence frame, then confirm on the next page."], scaffolds:"Prefix flip cards with icons; setting choices shown as pictures; sentence frame 'I think next ___'", monitor:"Prefix word accuracy (3/4); reasonable prediction confirmed or revised with 1 prompt", notes:"Ties to the Titanic/rescue theme carried through Week 1" },
      on:{ id:"U3W1-O", skill:"Analyzing plot & setting; using illustrations", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Below Deck: A Titanic Story (anchor text), plot-setting organizer", proc:["Revisit a section already read whole-class; identify setting and 1 plot event with the group.","Model how the illustration on that page adds information beyond the words.","Students find a second illustration and describe what it adds, with a partner.","Discuss how the setting (the ship) creates the story's problem.","Write 1-2 sentences on how setting affects the plot."], scaffolds:"Sentence frame 'The illustration shows ___, which tells me ___'; partner talk before independent write", monitor:"Written response checked for a clear setting-to-plot connection", notes:"Good push-in tie-in right after the whole-class first read" }
    },
    { w:2, genre:"Historical Fiction", text:"Granddaddy's Turn: A Journey to the Ballot Box", author:"by Michael S. Bandy and Eric Stein", wq:"How can a hero's actions affect other people?", comp:"Analyze Characters; Make Connections", vocab:"Words that Describe Characters (Synonyms and Antonyms)", word:"Abbreviations", craft:"Explain & Emphasize Author's Message", belowRes:"Foldable Decodable: \"The Bus Party\" | myFocus Reader: \"People Who Help Are Heroes\"",
      below:{ id:"U3W2-B", skill:"Character actions; abbreviations", fp:"K-L", lex:"280-420L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"The Bus Party\", myView myFocus Reader \"People Who Help Are Heroes\", abbreviation match cards", proc:["Review 3 common abbreviations (Mr., Dr., St.) with their full-word matches.","Echo-read \"The Bus Party,\" spotting abbreviations together.","Read myFocus Reader \"People Who Help Are Heroes\" in chunks.","After each chunk, ask 'What did this person do to help?' using a picture-supported choice.","Students point to or say their favorite helper's action."], scaffolds:"Abbreviation match cards; action choices shown as pictures; sentence frame '___ helped by ___'", monitor:"Abbreviation match accuracy (2/3); names 1 helping action with 1 prompt or less", notes:"Builds background for the whole-class 'hero's actions affect others' discussion" },
      on:{ id:"U3W2-O", skill:"Analyzing characters; making connections; author's message", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Granddaddy's Turn (anchor text), connections organizer, synonym/antonym cards", proc:["Revisit a key scene from the anchor text with the group.","Model making 1 personal or text-to-text connection to the character's experience.","Students make a second connection with a partner and record it.","Sort 4-6 vocabulary words into synonym/antonym pairs.","Discuss: what message do you think the author wants readers to take away? Write 1 sentence."], scaffolds:"Sentence frame 'This reminds me of ___ because ___'; partner talk before independent write", monitor:"Connection + message statement checked for text-based reasoning", notes:"Reinforces 'Analyze Characters / Make Connections' and 'Author's Message' objectives together" }
    },
    { w:3, genre:"Historical Fiction", text:"from Little House on the Prairie and By the Shores of Silver Lake", author:"by Laura Ingalls Wilder", wq:"How do challenges turn ordinary people into heroes?", comp:"Infer Theme; Compare and Contrast Texts", vocab:"Words that Engage Readers' Senses (Context Clues)", word:"Suffixes -ful, -y, -ness", craft:"Describe & Use Hyperbole", belowRes:"Foldable Decodable: \"Look Up!\" | myFocus Reader: \"A Family Hero\"",
      below:{ id:"U3W3-B", skill:"Comparing two short passages; suffixes -ful, -y, -ness", fp:"K-M", lex:"350-480L", wida:"2-4", format:"Push-In", size:"3-6", dur:20, materials:"myView Foldable Decodable \"Look Up!\", myView myFocus Reader \"A Family Hero\", suffix build cards", proc:["Review 1 suffix (-ful = full of) building 2-3 words together (careful, joyful).","Echo-read \"Look Up!\", circling suffix words.","Read myFocus Reader \"A Family Hero\" in chunks.","Students note 1 fact per chunk on a simple same/different chart comparing 2 family members' actions.","Share one fact using a sentence frame."], scaffolds:"Suffix build cards; same/different chart with icons; sentence frame 'This person ___'", monitor:"Suffix word accuracy (3/4); chart shows 2-3 accurate facts", notes:"Keep comparison to simple same/different rather than full compare-contrast at this level" },
      on:{ id:"U3W3-O", skill:"Inferring theme; comparing texts; hyperbole", fp:"N-P", lex:"580-720L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copies/excerpts of both anchor texts, theme organizer, hyperbole examples", proc:["Revisit a passage from each text with the group.","Model finding 1 example of hyperbole (exaggeration) and explaining what it really means.","Students find a second hyperbole example with a partner.","Discuss: what message about facing challenges do both texts share? Record on theme organizer.","Write 1-2 sentences comparing the theme across both texts."], scaffolds:"Sentence frame 'This is an exaggeration because ___. It really means ___'; partner talk before independent write", monitor:"Theme comparison checked for evidence from both texts", notes:"Directly reinforces 'Infer Theme / Compare and Contrast Texts' objective" }
    },
    { w:4, genre:"Biography", text:"Mama Miti: Wangari Maathai and the Trees of Kenya", author:"by Donna Jo Napoli", wq:"Why do people need heroes?", comp:"Analyze Text Structure; Summarize Informational Text", vocab:"Words that Make Connections", word:"Vowel Teams oo, ew, ue, ui, eu", craft:"Analyze & Use Voice and Tone", belowRes:"Foldable Decodable: \"Andrew and Sue Need a Rescue\" | myFocus Reader: \"A High-Flying Hero\"",
      below:{ id:"U3W4-B", skill:"Summarizing informational text; vowel teams (oo, ew, ue, ui, eu)", fp:"L-M", lex:"400-490L", wida:"2-4", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Andrew and Sue Need a Rescue\", myView myFocus Reader \"A High-Flying Hero\", vowel team sound cards", proc:["Review 2 vowel team sounds with picture-sound cards.","Echo-read \"Andrew and Sue Need a Rescue,\" finding target words together.","Read myFocus Reader \"A High-Flying Hero\" in chunks.","After reading, retell the text in order using 3 picture cards (beginning/middle/end).","Students summarize in 1 sentence using a frame."], scaffolds:"Vowel team sound-picture cards; 3-picture retell sequence; sentence frame 'First ___, then ___, in the end ___'", monitor:"Vowel team word accuracy (3/4); summary includes all 3 sequence parts", notes:"Keep summary to 3 simple parts rather than full structure analysis" },
      on:{ id:"U3W4-O", skill:"Analyzing text structure; voice and tone", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Mama Miti (anchor text), text-structure organizer, tone word bank", proc:["Revisit a section of the anchor text; identify its text structure (e.g., problem-solution or sequence) with the group.","Discuss the author's tone/voice in a specific passage using a tone word bank (hopeful, determined).","Students find a second passage with a partner and identify its tone.","Discuss how the structure supports summarizing the text.","Write a 2-sentence summary using the structure as a guide."], scaffolds:"Tone word bank with definitions; sentence frame 'The author sounds ___ because ___'; partner talk before independent write", monitor:"Summary checked for structure-based organization (beginning/problem, actions, result)", notes:"Reinforces 'Analyze Text Structure / Summarize' and 'Voice and Tone' objectives together" }
    },
    { w:5, genre:"Poetry", text:"Poems About Heroes", author:"by Folami Abiade, Mary E. Cronin, Nikki Grimes, Jennifer Trujillo, Charles R. Smith Jr.", wq:"What kinds of actions can be heroic?", comp:"Explain Poetic Characteristics; Monitor Comprehension", vocab:"Words that Describe People", word:"Irregular Plural Nouns", craft:"Analyze & Use Descriptive Language", belowRes:"Foldable Decodable: \"Misty Jack and the Rain\" | myFocus Reader: \"Kids Can Be Heroes, Too!\"",
      below:{ id:"U3W5-B", skill:"Poem features; irregular plural nouns", fp:"K-M", lex:"330-470L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Misty Jack and the Rain\", myView myFocus Reader \"Kids Can Be Heroes, Too!\", irregular plural picture cards (child/children, foot/feet)", proc:["Review 3 irregular plurals with picture cards (one vs. many).","Echo-read \"Misty Jack and the Rain,\" finding target words.","Read myFocus Reader \"Kids Can Be Heroes, Too!\" in chunks.","After each chunk, point out rhyme or repeated words if present, clapping the rhythm together.","Students pick their favorite heroic kid action from the text using a sentence frame."], scaffolds:"Irregular plural picture cards; clapping/rhythm to build phonological awareness; sentence frame 'This kid ___'", monitor:"Irregular plural accuracy (2/3); names 1 heroic action with support", notes:"Good lead-in to the whole-class poetry unit's focus on sound and rhythm" },
      on:{ id:"U3W5-O", skill:"Explaining poetic characteristics; descriptive language", fp:"N-O", lex:"520-650L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:20, materials:"Class copies/excerpts of 2 poems from Poems About Heroes (anchor text), poetic-elements chart, descriptive-language highlighter sheet", proc:["Revisit a poem already read whole-class; identify 1 poetic element (rhyme, repetition, line breaks) with the group.","Model highlighting 1 descriptive/sensory phrase and discussing the image it creates.","Students find a second descriptive phrase in a different poem with a partner.","Discuss how the poetic elements affect how the poem sounds/feels when read aloud.","Share the descriptive phrase and its image with the group."], scaffolds:"Poetic-elements chart with icons (repeat arrow, rhyme bell); sentence frame 'When I read ___, I picture/feel ___'", monitor:"Chart + shared response checked for accurate poetic element and descriptive language identification", notes:"Reinforces 'Explain Poetic Characteristics' and 'Analyze/Use Descriptive Language' objectives" }
    },
    { w:6, genre:"Project-Based Inquiry", text:"Be a Hero!", author:"", wq:"What makes a hero? (unit synthesis / research project)", comp:"Conduct Research: Search Engines; Refine Research: Paraphrasing and Quoting", vocab:"Use Academic Words", word:"Review: Suffixes / Prefixes", craft:"Explore and Plan Argumentative Writing", belowRes:"Leveled Research Articles: \"Heroes Aren't Just for Comic Books\", \"I'm a Volunteer!\", \"A Helping Hand\"",
      below:{ id:"U3W6-B", skill:"Reading a research article for key facts", fp:"K-M", lex:"350-480L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView leveled research article \"I'm a Volunteer!\" (or \"A Helping Hand\"), fact-finder sticky notes", proc:["Preview the article's title and photos; predict the topic.","Read aloud in short chunks, marking one key fact per chunk with a sticky note.","Students choose their favorite fact and tell why it's interesting, using a sentence frame.","Sort 3-4 facts into simple categories (e.g., 'ways to help').","Share one fact aloud with the group."], scaffolds:"Picture walk before reading; sentence frame 'One fact I learned is ___'; sorting mat with icons", monitor:"Teacher checklist: identifies 1 clear, accurate fact from the article", notes:"Feeds directly into the whole-class Week 6 'Be a Hero!' project" },
      on:{ id:"U3W6-O", skill:"Using search engines for research; paraphrasing and quoting", fp:"N-P", lex:"560-780L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"myView leveled research articles (\"Heroes Aren't Just for Comic Books\", \"A Helping Hand\"), note-taking organizer, paraphrase-vs-quote example cards", proc:["Review the difference between paraphrasing (own words) and quoting (exact words) with 1 example each.","Students skim an article with a partner and paraphrase 1 sentence in their own words.","Model choosing 1 short quote worth using exactly.","Partners find and record 1 quote-worthy sentence from a second article.","Share a paraphrase and a quote, discussing which was more useful and why."], scaffolds:"Sentence starters ('In my own words, ___', 'The article says, \"___\"'); partner talk before independent work", monitor:"Note-taking organizer checked for 1 accurate paraphrase and 1 correctly marked quote", notes:"Directly supports the whole-class Week 6 argumentative opinion speech project" }
    }
  ]
});
