// data_u2.js — Unit 2: Interactions (Life Science)
window.HR_UNITS = window.HR_UNITS || [];
window.HR_UNITS.push({
  title: "Unit 2: Interactions",
  eq: "How do plants and animals live together?",
  weeks: [
    { w:1, genre:"Informational Text", text:"Patterns in Nature", author:"by Jennifer Rozines Roy and Gregory Roy", wq:"How do patterns in nature help plants and animals?", comp:"Identify Main Idea and Details; Monitor Comprehension", vocab:"Domain-Specific Words (Related Words)", word:"Syllable Patterns VC/V and V/CV", craft:"Explain & Use Graphic Features", belowRes:"Foldable Decodable: \"A Trip to the Moon\" | myFocus Reader: \"Sometimes It's Good to Blend In\"",
      below:{ id:"U2W1-B", skill:"Main idea & details; syllable patterns (VC/V, V/CV)", fp:"J-K", lex:"BR-330L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"A Trip to the Moon\", myView myFocus Reader \"Sometimes It's Good to Blend In\", syllable-split cards", proc:["Review VC/V vs. V/CV syllable split with 2-3 sample words, sorting which syllable is 'open' or 'closed.'","Echo-read \"A Trip to the Moon,\" splitting target words together.","Read myFocus Reader \"Sometimes It's Good to Blend In\" in chunks.","After each chunk, ask 'What is this mostly about?' using a 2-choice picture prompt.","Students pick the best main-idea picture/sentence for the whole text."], scaffolds:"Syllable-split cards color-coded by pattern; main-idea choices shown as pictures, not open-ended; choral read before independent choice", monitor:"Syllable split accuracy (3/4 words); correct main-idea choice with 1 prompt or less", notes:"Ties to Week 1's 'blending in' science theme (camouflage) which recurs later in the unit" },
      on:{ id:"U2W1-O", skill:"Main idea & details; graphic features", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Patterns in Nature (anchor text), main idea 'hamburger' organizer, graphic-feature scavenger sheet", proc:["Revisit a section of the anchor text already read whole-class; identify 1 graphic feature (diagram, photo, caption) and what it adds.","Model stating the main idea of that section with 1 supporting detail.","Students find 2 more details with a partner and add them to the organizer.","Discuss how the graphic feature supports the main idea.","Write a 1-2 sentence summary using the organizer."], scaffolds:"Sentence frame 'This section is mostly about ___. One detail is ___'; partner talk before independent write", monitor:"Organizer + summary checked for a main idea supported by at least 2 accurate details", notes:"Reinforces the week's 'Identify Main Idea and Details / Monitor Comprehension' objective directly" }
    },
    { w:2, genre:"Informational Text", text:"Weird Friends: Unlikely Allies in the Animal Kingdom", author:"by Jose Aruego and Ariane Dewey", wq:"How do living things in a habitat support one another?", comp:"Analyze Text Structure; Evaluate Details", vocab:"Scientific Words that Describe Things (Synonyms and Antonyms)", word:"r-Controlled Vowels", craft:"Analyze & Use Precise Verbs", belowRes:"Foldable Decodable: \"Marco Makes Art\" | myFocus Reader: \"A City Safari\"",
      below:{ id:"U2W2-B", skill:"Text structure basics; r-controlled vowels", fp:"K-L", lex:"280-420L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Marco Makes Art\", myView myFocus Reader \"A City Safari\", r-controlled vowel sound cards (ar, or, er/ir/ur)", proc:["Review 2 r-controlled vowel sounds with picture-sound cards.","Echo-read \"Marco Makes Art,\" circling target words.","Read myFocus Reader \"A City Safari\" in chunks, noting whether each page compares two things, describes a problem, or lists facts (simple structure ID with picture icons).","Students match a page to a structure icon with partner support.","Share out using a sentence frame."], scaffolds:"Structure icons (scale = compare, list = facts, arrow = sequence); r-controlled vowel cards kept visible; choral read first", monitor:"r-controlled word accuracy (4/5); correct structure-icon match for 2 of 3 pages", notes:"Keep structure choices to 2-3 options max at this level" },
      on:{ id:"U2W2-O", skill:"Analyze text structure; evaluate details; synonyms/antonyms", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Weird Friends (anchor text), text-structure sort cards, synonym/antonym word pairs", proc:["Revisit a section of the anchor text; identify its text structure (e.g., compare/contrast) with the group.","Discuss which details are most important vs. just interesting, modeling with 1 example.","Students sort 6 vocabulary words from the text into synonym/antonym pairs with a partner.","Evaluate 2 more details together, deciding if each is essential to understanding the topic.","Write 1 sentence stating the most important detail and why."], scaffolds:"Sentence frame 'This detail matters most because ___'; structure anchor chart visible; partner talk before independent write", monitor:"Written response checked for a clearly justified 'most important' detail", notes:"Directly reinforces 'Analyze Text Structure / Evaluate Details' objective" }
    },
    { w:3, genre:"Realistic Fiction", text:"Wolf Island", author:"by Celia Godkin", wq:"How can a chain of events affect plants and animals?", comp:"Analyze Illustrations; Synthesize Information", vocab:"Words that Connect Ideas (Context Clues)", word:"Compound Words", craft:"Analyze & Use Author's Message", belowRes:"Foldable Decodable: \"At the Pond\" | myFocus Reader: \"Beach Rescue\"",
      below:{ id:"U2W3-B", skill:"Using illustrations to understand text; compound words", fp:"K-M", lex:"350-480L", wida:"2-4", format:"Push-In", size:"3-6", dur:20, materials:"myView Foldable Decodable \"At the Pond\", myView myFocus Reader \"Beach Rescue\", compound word puzzle cards", proc:["Review compound words by building 3 examples from 2 smaller word cards (sun + set = sunset).","Echo-read \"At the Pond,\" finding compound words together.","Read myFocus Reader \"Beach Rescue\" in chunks; before reading each page's text, look closely at the photo/illustration and predict what's happening.","Confirm or adjust prediction after reading the text.","Students describe what one illustration shows using a sentence frame."], scaffolds:"Compound word puzzle pieces students physically combine; sentence frame 'The picture shows ___'; picture-first approach builds language before text", monitor:"Compound word accuracy (3/4 built correctly); reasonable prediction from 2 of 3 illustrations", notes:"Good push-in tie-in to the whole-class 'Analyze Illustrations' focus" },
      on:{ id:"U2W3-O", skill:"Analyze illustrations; synthesize information; context clues", fp:"N-P", lex:"580-720L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Wolf Island (anchor text), illustration-text connection organizer, context-clue bookmark", proc:["Revisit a spread from the anchor text; discuss what the illustration adds beyond the words.","Model synthesizing: combine 1 detail from text + 1 detail from illustration into one bigger idea.","Students find a second illustration-text combo with a partner and record their synthesized idea.","Use the context-clue bookmark to figure out 1 unfamiliar word from the same page.","Share the synthesized idea with the group."], scaffolds:"Organizer with 2 boxes (Text says... / Picture shows...) merging into 1 'Big idea' box; sentence frame provided", monitor:"Organizer checked for a synthesized idea that draws on both text and illustration", notes:"Directly reinforces 'Analyze Illustrations / Synthesize Information' objective" }
    },
    { w:4, genre:"Persuasive Text", text:"Welcome Back, Wolves! / Wolves Don't Belong in Yellowstone", author:"by Pooja Makhijani / by Frances Ruffin", wq:"How does reintroduction of a species affect plants and animals in a habitat?", comp:"Analyze Text Structure; Compare and Contrast Texts", vocab:"Synonyms and Antonyms", word:"Syllable Patterns", craft:"Analyze & Use Tone and Voice", belowRes:"Foldable Decodable: \"Our Water\" | myFocus Reader: \"Habitat Species\"",
      below:{ id:"U2W4-B", skill:"Comparing two short texts; syllable patterns", fp:"L-M", lex:"400-490L", wida:"2-4", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Our Water\", myView myFocus Reader \"Habitat Species\", 2-column same/different chart", proc:["Review a syllable pattern from this week's word study with 2-3 example words.","Echo-read \"Our Water,\" tapping out target words.","Read myFocus Reader \"Habitat Species\" in chunks.","Students note 1 fact per chunk on a simple same/different chart, comparing to what they already know about animals in habitats.","Share one fact using a sentence frame."], scaffolds:"Same/different chart with picture icons; sentence frame 'This animal ___'; choral read before independent chart work", monitor:"Chart shows 2-3 accurate facts; syllable pattern accuracy (3/4 words)", notes:"Keep comparison simple (same/different) rather than full compare-contrast at this level" },
      on:{ id:"U2W4-O", skill:"Compare and contrast two persuasive texts", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copies/excerpts of both anchor texts, T-chart, synonym/antonym cards", proc:["Revisit each text's main argument (already introduced whole-class) with the group.","Model recording 1 point from each text on a T-chart.","Students add 2 more points each with a partner.","Sort 4-6 vocabulary words shared across both texts into synonym/antonym pairs.","Write 1-2 sentences comparing the two authors' viewpoints using a frame."], scaffolds:"Sentence frame 'One author thinks ___, while the other thinks ___'; T-chart color-coded by text; partner talk before independent write", monitor:"Written comparison checked for one clear point from each text", notes:"Reinforces the week's 'Analyze Text Structure / Compare and Contrast Texts' objective directly" }
    },
    { w:5, genre:"Informational Text", text:"Nature's Patchwork Quilt", author:"by Mary Mich\u00e9", wq:"Why is it important for plants and animals to depend on each other?", comp:"Explain Author's Purpose; Visualize Details", vocab:"Related Words", word:"Contractions", craft:"Analyze Text Structure; Use Cause-and-Effect Text Structure", belowRes:"Foldable Decodable: \"Ric Cleans Up\" | myFocus Reader: \"Plants and Animals Rely on Each Other\"",
      below:{ id:"U2W5-B", skill:"Visualizing details; contractions", fp:"K-M", lex:"330-470L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Ric Cleans Up\", myView myFocus Reader \"Plants and Animals Rely on Each Other\", contraction match cards", proc:["Review 3 contractions and their 2-word matches with cards (do not/don't).","Echo-read \"Ric Cleans Up,\" finding contractions together.","Read myFocus Reader \"Plants and Animals Rely on Each Other\" in chunks; after each chunk, close eyes briefly and describe what you 'see' in your mind.","Students draw a quick picture of what they visualized for 1 chunk.","Share drawing with a partner using a sentence frame."], scaffolds:"Contraction match cards; sentence frame 'I picture ___'; drawing accepted as full response to lower language demand", monitor:"Contraction match accuracy (3/4); drawing reasonably matches text content for 1 chunk", notes:"Pairs the phonics skill (contractions) with the comprehension skill (visualizing) in the same short block" },
      on:{ id:"U2W5-O", skill:"Author's purpose; visualizing; cause-and-effect structure", fp:"N-P", lex:"560-750L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Nature's Patchwork Quilt (anchor text), cause-effect organizer, PIE (persuade/inform/entertain) chart", proc:["Revisit a descriptive passage from the anchor text; highlight 1-2 vivid phrases as a group.","Discuss what the author's purpose is for including this level of detail (PIE chart).","Students find a cause-and-effect pair from the text with a partner and record it on an organizer.","Discuss how the cause-effect structure supports the author's purpose.","Write 1 sentence describing a mental picture the text creates."], scaffolds:"Sentence frame 'When I read ___, I picture ___'; PIE icons visible; partner talk before independent write", monitor:"Cause-effect organizer + sentence checked for text-based accuracy", notes:"Reinforces 'Explain Author's Purpose / Visualize Details' and the cause-and-effect text structure focus" }
    },
    { w:6, genre:"Project-Based Inquiry", text:"Make Note of It!", author:"", wq:"How do plants and animals live together? (unit synthesis / research project)", comp:"Conduct Research: Library Databases; Refine Research: Citing Sources", vocab:"Use Academic Words", word:"Review: Syllable Patterns / Contractions", craft:"Explore and Plan Informational Writing", belowRes:"Leveled Research Articles: \"Relationships in Nature\", \"Coral Reefs: Living Environments\", \"Why We Need Plants\"",
      below:{ id:"U2W6-B", skill:"Reading a research article for key facts", fp:"K-M", lex:"350-480L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView leveled research article \"Why We Need Plants\" (or \"Coral Reefs: Living Environments\"), fact-finder sticky notes", proc:["Preview the article's title and photos; predict the topic.","Read aloud in short chunks, marking one key fact per chunk with a sticky note.","Students choose their favorite fact and tell why it's interesting, using a sentence frame.","Sort 3-4 facts into simple categories (e.g., 'about plants' / 'about animals') as a pre-research organizer.","Share one fact aloud with the group."], scaffolds:"Picture walk before reading; sentence frame 'One fact I learned is ___'; sorting mat with icons instead of only text", monitor:"Teacher checklist: identifies 1 clear, accurate fact from the article", notes:"Feeds directly into the whole-class Week 6 research/scrapbook project" },
      on:{ id:"U2W6-O", skill:"Using library databases; citing sources; taking notes", fp:"N-P", lex:"560-780L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"myView leveled research articles (\"Relationships in Nature\", \"Coral Reefs: Living Environments\"), note-taking organizer, source-citation card", proc:["Review what a citation needs (title, author if known) with 1 example.","Students skim an article with a partner and record its title/source on a citation card.","Model taking 2 notes (not full sentences) from a source, in their own words.","Partners take 2 notes of their own from a second article, citing the source.","Share one note aloud and discuss how it could support the class informational scrapbook project."], scaffolds:"Note-taking sentence starters ('One reason ___', 'This source says ___'); partner talk before independent note-taking", monitor:"Note-taking organizer checked for 2 accurate notes with sources cited", notes:"Directly supports the whole-class Week 6 informational writing/research project" }
    }
  ]
});
