// data_u4.js — Unit 4: Events (History)
window.HR_UNITS = window.HR_UNITS || [];
window.HR_UNITS.push({
  title: "Unit 4: Events",
  eq: "How do communities change over time?",
  weeks: [
    { w:1, genre:"Biography", text:"The House That Jane Built", author:"by Tanya Lee Stone", wq:"How can one person improve a community?", comp:"Analyze Text Structure; Correct or Confirm Predictions", vocab:"Words That Explain Main Ideas (Related Words)", word:"r-Controlled Vowels ir, er, ur, ear", craft:"Explain & Use Descriptive Language", belowRes:"Foldable Decodable: \"Clouds in the Sky\" | myFocus Reader: \"Shopping Mall Surprise!\"",
      below:{ id:"U4W1-B", skill:"Text structure basics; r-controlled vowels (ir, er, ur, ear)", fp:"J-K", lex:"BR-330L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Clouds in the Sky\", myView myFocus Reader \"Shopping Mall Surprise!\", r-controlled vowel sound cards", proc:["Review 2 r-controlled vowel sounds with picture-sound cards.","Echo-read \"Clouds in the Sky,\" circling target words.","Read myFocus Reader \"Shopping Mall Surprise!\" in chunks.","After each chunk, ask 'What do you think happens next?' using a 2-picture choice.","Confirm prediction on the next page and celebrate/adjust."], scaffolds:"r-controlled vowel cards kept visible; prediction choices shown as pictures; sentence frame 'I think ___'", monitor:"r-controlled word accuracy (3/4); reasonable prediction with 1 prompt or less", notes:"Builds prediction-making skill needed for the whole-class biography structure work" },
      on:{ id:"U4W1-O", skill:"Analyzing text structure; descriptive language", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of The House That Jane Built (anchor text), text-structure organizer, descriptive-language highlighter sheet", proc:["Revisit a section already read whole-class; identify its text structure (e.g., chronological/sequence) with the group.","Model highlighting 1 descriptive phrase and discussing what it adds.","Students find a second descriptive phrase with a partner.","Discuss how the structure helps readers understand how Jane Addams improved her community.","Write 1-2 sentences summarizing using the structure."], scaffolds:"Sentence frame 'First ___, then ___, which shows ___'; partner talk before independent write", monitor:"Written summary checked for structure-based organization and 1 descriptive detail", notes:"Reinforces 'Analyze Text Structure' and 'Descriptive Language' objectives together" }
    },
    { w:2, genre:"Biography", text:"from Frederick Douglass", author:"by Josh Gregory", wq:"How can personal stories change society?", comp:"Identify Main Idea and Key Details; Make Inferences", vocab:"Words That Explain Events in a Person's Life (Synonyms and Antonyms)", word:"VCCCV Pattern", craft:"Analyze & Use Graphic Features", belowRes:"Foldable Decodable: \"Jess's Story\" | myFocus Reader: \"A First Lady Moves On\"",
      below:{ id:"U4W2-B", skill:"Main idea; VCCCV syllable pattern", fp:"K-L", lex:"280-420L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Jess's Story\", myView myFocus Reader \"A First Lady Moves On\", VCCCV syllable split cards", proc:["Review the VCCCV pattern (e.g., hundred) splitting 2-3 example words together.","Echo-read \"Jess's Story,\" splitting target words.","Read myFocus Reader \"A First Lady Moves On\" in chunks.","After each chunk, ask 'What is this mostly about?' using a 2-choice picture prompt.","Students pick the best main-idea choice for the whole text."], scaffolds:"Syllable-split cards; main-idea choices shown as pictures; choral read before independent choice", monitor:"Syllable split accuracy (3/4); correct main-idea choice with 1 prompt or less", notes:"Keep main idea choices simple/concrete at this level" },
      on:{ id:"U4W2-O", skill:"Identifying main idea & key details; making inferences; graphic features", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Frederick Douglass biography (anchor text), main idea organizer, inference clue cards", proc:["Revisit a section of the anchor text; identify main idea with 1 supporting detail as a group.","Model making 1 inference about how Douglass felt, citing a text clue.","Students find a second detail and a second inference with a partner.","Discuss how a graphic feature (photo, timeline) supports the main idea.","Write 1-2 sentences using the organizer."], scaffolds:"Sentence frame 'I can infer ___ because the text says ___'; partner talk before independent write", monitor:"Organizer + written response checked for accurate main idea, detail, and inference", notes:"Reinforces 'Identify Main Idea and Key Details / Make Inferences' objective directly" }
    },
    { w:3, genre:"Biography", text:"from Milton Hershey", author:"by Charnan Simon", wq:"How do big ideas change communities?", comp:"Explain Author's Purpose; Ask and Answer Questions", vocab:"Descriptive Words (Context Clues)", word:"Latin Suffixes", craft:"Explain & Use Tone and Voice", belowRes:"Foldable Decodable: \"Gram's Vacation Plan\" | myFocus Reader: \"Spring Break at Home\"",
      below:{ id:"U4W3-B", skill:"Author's purpose basics; Latin suffixes", fp:"K-M", lex:"350-480L", wida:"2-4", format:"Push-In", size:"3-6", dur:20, materials:"myView Foldable Decodable \"Gram's Vacation Plan\", myView myFocus Reader \"Spring Break at Home\", Latin suffix cards (-tion, -ment)", proc:["Review 1 Latin suffix and its meaning with 2 example words.","Echo-read \"Gram's Vacation Plan,\" finding target words.","Read myFocus Reader \"Spring Break at Home\" in chunks.","After reading, ask 'Why do you think the author wrote this?' using PIE picture icons (persuade/inform/entertain).","Students pick the best purpose icon and share why."], scaffolds:"Latin suffix cards; PIE icons kept visible; sentence frame 'The author wants to ___'", monitor:"Suffix word accuracy (2/3); reasonable purpose choice with 1 piece of evidence", notes:"Keep author's purpose to the simple PIE framework at this level" },
      on:{ id:"U4W3-O", skill:"Explaining author's purpose; asking and answering questions; tone and voice", fp:"N-P", lex:"580-720L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Milton Hershey biography (anchor text), Q&A organizer, tone word bank", proc:["Revisit a section of the anchor text; generate 1 question about it with the group and answer it using text evidence.","Students generate and answer a second question with a partner.","Discuss the author's tone in a specific passage using the tone word bank.","Discuss why the author chose to write about Hershey's big idea.","Write 1 sentence stating the author's purpose with evidence."], scaffolds:"Question stems ('Why did...', 'How did...'); sentence frame 'The author's purpose is ___ because ___'", monitor:"Q&A organizer + purpose statement checked for text-based accuracy", notes:"Directly reinforces 'Explain Author's Purpose / Ask and Answer Questions' objective" }
    },
    { w:4, genre:"Narrative Nonfiction", text:"Green City", author:"by Allan Drummond", wq:"How can a leader's experiences inspire change?", comp:"Distinguish Viewpoint; Make Connections", vocab:"Words That Help Readers Connect Events (Analogies)", word:"Homographs", craft:"Analyze & Use Text Structure", belowRes:"Foldable Decodable: \"The Perfect Present\" | myFocus Reader: \"Try and Try Again\"",
      below:{ id:"U4W4-B", skill:"Making connections; homographs", fp:"L-M", lex:"400-490L", wida:"2-4", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"The Perfect Present\", myView myFocus Reader \"Try and Try Again\", homograph picture pairs (bat/bat, bark/bark)", proc:["Review 2 homographs using picture pairs showing both meanings.","Echo-read \"The Perfect Present,\" finding target words and discussing which meaning fits.","Read myFocus Reader \"Try and Try Again\" in chunks.","After each chunk, ask 'Does this remind you of anything?' using picture prompts (weather, rebuilding, trying again).","Students share 1 connection using a sentence frame."], scaffolds:"Homograph picture pairs; connection picture prompts; sentence frame 'This reminds me of ___'", monitor:"Homograph meaning identification (1/2 correct); makes 1 reasonable connection with support", notes:"Keep connections concrete and personal (weather, community) rather than abstract" },
      on:{ id:"U4W4-O", skill:"Distinguishing viewpoint; analyzing text structure", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Green City (anchor text), viewpoint organizer, text-structure cards", proc:["Revisit a section of the anchor text; identify whose viewpoint is being shared with the group.","Model identifying the text structure (e.g., cause-effect: tornado \u2192 rebuilding) with 1 example.","Students find a second cause-effect example with a partner.","Discuss how understanding the leader's viewpoint helps explain the community's choices.","Write 1-2 sentences on how the leader's experience inspired change."], scaffolds:"Sentence frame 'From ___'s viewpoint, ___ happened because ___'; partner talk before independent write", monitor:"Written response checked for a text-based viewpoint and cause-effect connection", notes:"Reinforces 'Distinguish Viewpoint / Make Connections' and text-structure objectives together" }
    },
    { w:5, genre:"Drama", text:"Grace and Grandma", author:"by Rich Lo", wq:"How do people support each other in difficult times?", comp:"Identify Play Elements; Monitor Comprehension", vocab:"Precise Words (Homophones)", word:"Homophones", craft:"Explain Author's Message; Share a Message", belowRes:"Foldable Decodable: \"Where Is Paige's Page?\" | myFocus Reader: \"Music from Trash\"",
      below:{ id:"U4W5-B", skill:"Play elements basics; homophones", fp:"K-M", lex:"330-470L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Where Is Paige's Page?\", myView myFocus Reader \"Music from Trash\", homophone match cards (there/their, hear/here)", proc:["Review 2 homophone pairs with picture cards showing the difference.","Echo-read \"Where Is Paige's Page?\", finding target words.","Read myFocus Reader \"Music from Trash\" in chunks.","Point out that plays have characters and lines like a script; model reading a line with expression.","Students echo-read 1 line with expression."], scaffolds:"Homophone picture cards; punctuation-cue reminders for expression; echo-read before independent try", monitor:"Homophone match accuracy (2/3); reads 1 line with reasonable expression", notes:"Light introduction to drama/play format before the whole-class Grace and Grandma reading" },
      on:{ id:"U4W5-O", skill:"Identifying play elements; author's message", fp:"N-P", lex:"560-750L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Grace and Grandma (anchor text — drama), play-elements chart, message organizer", proc:["Revisit a scene from the play already read whole-class; identify 1 play element (stage directions, dialogue, scene) with the group.","Partner-read a short section of dialogue with expression.","Discuss what message the playwright wants to share about supporting each other.","Students find 1 line of dialogue that supports the message.","Write 1 sentence sharing the message with evidence."], scaffolds:"Play-elements chart with icons; sentence frame 'The message is ___. I know because ___ said, \"___\"'", monitor:"Message statement checked for text-based evidence from dialogue", notes:"Directly reinforces 'Identify Play Elements' and 'Author's Message / Share a Message' objectives" }
    },
    { w:6, genre:"Project-Based Inquiry", text:"Past and Present", author:"", wq:"How do communities change over time? (unit synthesis / research project)", comp:"Conduct Research: Library of Congress; Refine Research: Identifying Sources", vocab:"Use Academic Words", word:"Review: Homophones / Homographs", craft:"Explore and Plan Informational Writing", belowRes:"Leveled Research Articles: \"From Wood to Stone\", \"Yankee Stadium: Then and Now\", \"History in the Making\"",
      below:{ id:"U4W6-B", skill:"Reading a research article for key facts", fp:"K-M", lex:"350-480L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView leveled research article \"From Wood to Stone\" (or \"Yankee Stadium: Then and Now\"), fact-finder sticky notes", proc:["Preview the article's title and photos; predict the topic.","Read aloud in short chunks, marking one key fact per chunk with a sticky note.","Students choose their favorite fact and tell why, using a sentence frame.","Sort 3-4 facts into 'then' vs. 'now' categories as a simple pre-research organizer.","Share one fact aloud with the group."], scaffolds:"Picture walk before reading; sentence frame 'One fact I learned is ___'; then/now sorting mat with icons", monitor:"Teacher checklist: identifies 1 clear, accurate fact and sorts it correctly (then/now)", notes:"Feeds directly into the whole-class Week 6 'Past and Present' project" },
      on:{ id:"U4W6-O", skill:"Using Library of Congress sources; identifying sources", fp:"N-P", lex:"560-780L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"myView leveled research articles (\"History in the Making\", \"Yankee Stadium: Then and Now\"), source-identification card, note-taking organizer", proc:["Review what makes a source reliable (author, date, organization) with 1 example.","Students skim an article with a partner and record its source information.","Model taking 2 notes in their own words from a source.","Partners take 2 notes of their own from a second article, recording the source.","Share one note aloud and discuss how it could support the class informational poster project."], scaffolds:"Note-taking sentence starters ('One reason ___', 'This source says ___'); partner talk before independent note-taking", monitor:"Note-taking organizer checked for 2 accurate notes with sources identified", notes:"Directly supports the whole-class Week 6 informational writing/poster project" }
    }
  ]
});
