// data_u5.js — Unit 5: Solutions (Earth Science)
window.HR_UNITS = window.HR_UNITS || [];
window.HR_UNITS.push({
  title: "Unit 5: Solutions",
  eq: "How does the world challenge us?",
  weeks: [
    { w:1, genre:"Informational Text", text:"Deep Down and Other Extreme Places to Live", author:"by Shirin Yim Bridges", wq:"How can nature change people's lives?", comp:"Analyze Text Features; Correct or Confirm Predictions", vocab:"Words That Describe or Explain a Topic (Related Words)", word:"Vowel Patterns au, aw, al, augh, ough", craft:"Explain & Use Text Features", belowRes:"Foldable Decodable: \"Birdie and the Big Show\" | myFocus Reader: \"The Nature Effect\"",
      below:{ id:"U5W1-B", skill:"Text features; vowel patterns (au, aw, al, augh, ough)", fp:"J-K", lex:"BR-330L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Birdie and the Big Show\", myView myFocus Reader \"The Nature Effect\", vowel pattern sound cards", proc:["Review 2 vowel pattern sounds (au/aw) with picture-sound cards.","Echo-read \"Birdie and the Big Show,\" circling target words.","Preview myFocus Reader \"The Nature Effect\": point out 1 text feature (photo, heading) before reading.","Read in chunks, naming what each text feature tells the reader.","Students match 2 text features to picture cards."], scaffolds:"Vowel pattern sound cards; text-feature icons (camera = photo, flag = heading); picture-match instead of definitions", monitor:"Vowel pattern word accuracy (3/4); correct text-feature match (2/3)", notes:"Sets up the whole-class text-features focus for the week" },
      on:{ id:"U5W1-O", skill:"Analyzing text features; correcting/confirming predictions", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Deep Down and Other Extreme Places to Live (anchor text), text-feature scavenger hunt, prediction organizer", proc:["Revisit 2 text features already introduced whole-class.","Model making a prediction based on a heading/photo, then confirming or revising it after reading.","Students complete a scavenger hunt finding 2 more features with a partner.","Discuss which feature was most helpful for predicting content.","Write 1 sentence using text evidence to answer 'How can nature change people's lives?'"], scaffolds:"Sentence frame 'Based on ___, I predicted ___. The text confirmed/changed this because ___'; partner talk before independent write", monitor:"Scavenger hunt sheet + final sentence checked for accurate text evidence", notes:"Strong push-in option since it reuses the whole-class anchor text directly" }
    },
    { w:2, genre:"Informational Text", text:"from Earthquakes, Eruptions, and Other Events that Change Earth", author:"by Natalie Hyde", wq:"How do changes on Earth affect the environment?", comp:"Analyze Text Structure; Synthesize Information", vocab:"Words That Describe Events That Affect Earth (Synonyms and Antonyms)", word:"Vowel Patterns ei, eigh", craft:"Analyze & Use Graphic Features", belowRes:"Foldable Decodable: \"The Reindeer Farm\" | myFocus Reader: \"Earth and Our Environment\"",
      below:{ id:"U5W2-B", skill:"Text structure basics; vowel patterns ei, eigh", fp:"K-L", lex:"280-420L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"The Reindeer Farm\", myView myFocus Reader \"Earth and Our Environment\", vowel pattern sound cards (ei/eigh)", proc:["Review the ei/eigh sound with 2-3 example words and picture cards.","Echo-read \"The Reindeer Farm,\" circling target words.","Read myFocus Reader \"Earth and Our Environment\" in chunks, noting whether each page describes a cause or an effect using picture icons.","Students match a page to a cause/effect icon with partner support.","Share out using a sentence frame."], scaffolds:"Cause/effect icons (arrow = 'leads to'); vowel pattern cards kept visible; choral read first", monitor:"Vowel pattern word accuracy (2/3); correct cause/effect match for 2 of 3 pages", notes:"Keep structure choices to cause vs. effect only at this level" },
      on:{ id:"U5W2-O", skill:"Analyzing text structure; synthesizing information; graphic features", fp:"N-O", lex:"560-680L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of Earthquakes, Eruptions... (anchor text), cause-effect chain organizer, graphic-feature notes", proc:["Revisit a section of the anchor text; identify a cause-effect chain with the group.","Model synthesizing: combine 1 detail from the text + 1 detail from a graphic (diagram, map) into 1 bigger idea.","Students find a second cause-effect example with a partner and record it.","Discuss how the graphic feature supports understanding the structure.","Write 1-2 sentences synthesizing text + graphic information."], scaffolds:"Sentence frame 'The text says ___, and the diagram shows ___, so ___'; partner talk before independent write", monitor:"Organizer + written response checked for a synthesized, text-based idea", notes:"Reinforces 'Analyze Text Structure / Synthesize Information' objective directly" }
    },
    { w:3, genre:"Procedural Text", text:"A Safety Plan: In Case of Emergency", author:"by Marcie Rendon", wq:"What are some ways to prepare for an emergency?", comp:"Analyze Text Structure; Monitor Comprehension", vocab:"Precise Words That Tell How to Do Something (Context Clues)", word:"Words with Suffix -en", craft:"Explain Use of Text Structure; Use Text Structure", belowRes:"Foldable Decodable: \"Pet Cats\" | myFocus Reader: \"Be Ready for Anything\"",
      below:{ id:"U5W3-B", skill:"Following a procedure; suffix -en", fp:"K-M", lex:"350-480L", wida:"2-4", format:"Push-In", size:"3-6", dur:20, materials:"myView Foldable Decodable \"Pet Cats\", myView myFocus Reader \"Be Ready for Anything\", -en suffix cards (soften, harden)", proc:["Review the suffix -en and its meaning ('to make') with 2-3 example words.","Echo-read \"Pet Cats,\" finding target words.","Read myFocus Reader \"Be Ready for Anything\" in chunks, following the steps with numbered picture cards.","Students place picture steps in order on a pocket chart.","Group retells the steps using time-order words."], scaffolds:"-en suffix cards; numbered picture step cards; sentence frame 'First ___, then ___'", monitor:"Suffix word accuracy (2/3); correctly orders 3/4 steps", notes:"Pairs well with a simple classroom emergency-drill discussion" },
      on:{ id:"U5W3-O", skill:"Analyzing procedural text structure; monitoring comprehension", fp:"N-P", lex:"560-750L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:25, materials:"Class copy/excerpt of A Safety Plan: In Case of Emergency (anchor text), step-sequence organizer, precise-words list", proc:["Revisit the anchor text's numbered/sequenced steps with the group.","Model 1 comprehension-monitoring strategy (rereading a confusing step, asking 'What does this mean?').","Students practice the same strategy on a second step with a partner.","Discuss why precise words (exactly, immediately) matter in a safety plan.","Write a 2-3 step mini safety plan of their own using precise words."], scaffolds:"Sentence frame 'I re-read this part because ___'; precise-word bank kept visible; partner talk before independent write", monitor:"Mini safety plan checked for clear, ordered steps with at least 1 precise word", notes:"Directly reinforces 'Analyze Text Structure / Monitor Comprehension' for procedural text" }
    },
    { w:4, genre:"Historical Fiction", text:"Nora's Ark", author:"by Natalie Kinsey-Warnock", wq:"How should people respond during a disaster?", comp:"Analyze Point of View; Make Connections", vocab:"Words That Add Details about Characters' Experiences (Figurative Language)", word:"Schwa", craft:"Analyze & Use Voice", belowRes:"Foldable Decodable: \"A Game of Hide and Seek\" | myFocus Reader: \"How to Help During a Disaster\"",
      below:{ id:"U5W4-B", skill:"Making connections; schwa sound", fp:"L-M", lex:"400-490L", wida:"2-4", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"A Game of Hide and Seek\", myView myFocus Reader \"How to Help During a Disaster\", schwa sound cards (about, pencil)", proc:["Review the schwa sound with 2-3 example words, tapping the 'uh' sound together.","Echo-read \"A Game of Hide and Seek,\" finding target words.","Read myFocus Reader \"How to Help During a Disaster\" in chunks.","After each chunk, ask 'Has something like this ever happened to you or someone you know?' using picture prompts (storm, flood, helping).","Students share 1 connection using a sentence frame."], scaffolds:"Schwa sound cards; connection picture prompts; sentence frame 'This reminds me of ___'", monitor:"Schwa word recognition (2/3); makes 1 reasonable connection with support", notes:"Keep disaster-related content age-appropriate and non-distressing; focus on helping, not danger" },
      on:{ id:"U5W4-O", skill:"Analyzing point of view; making connections; voice", fp:"N-O", lex:"540-660L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"Class copy/excerpt of Nora's Ark (anchor text), point-of-view organizer, voice word bank", proc:["Revisit a section of the anchor text; identify whose point of view the story is told from.","Model making 1 connection to the character's experience during the flood.","Students find a second point-of-view clue with a partner.","Discuss the narrator's voice using the word bank (worried, brave, calm).","Write 1-2 sentences describing the character's point of view and how it's expressed."], scaffolds:"Sentence frame 'The story is told from ___'s point of view. I know because ___'; partner talk before independent write", monitor:"Written response checked for accurate point-of-view identification with text evidence", notes:"Reinforces 'Analyze Point of View / Make Connections' and 'Voice' objectives together" }
    },
    { w:5, genre:"Traditional Tale: Fable", text:"from Aesop's Fox", author:"retold by Aki Sogabe", wq:"What can nature teach us about ourselves?", comp:"Infer Theme; Evaluate Details", vocab:"Words That Describe Characters and Events (Parts of Speech)", word:"Final Stable Syllables -le, -ture, -ive, -ize", craft:"Describe Use of Imagery; Use Precise Verbs", belowRes:"Foldable Decodable: \"Amy's Adventure\" | myFocus Reader: \"On the Hunt for a Survival Plan\"",
      below:{ id:"U5W5-B", skill:"Fable basics; final stable syllables (-le, -ture, -ive, -ize)", fp:"K-M", lex:"330-470L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView Foldable Decodable \"Amy's Adventure\", myView myFocus Reader \"On the Hunt for a Survival Plan\", syllable pattern cards", proc:["Review 1 final stable syllable pattern (-le, e.g., little/table) with 2-3 example words.","Echo-read \"Amy's Adventure,\" splitting target words.","Read myFocus Reader \"On the Hunt for a Survival Plan\" in chunks.","After reading, ask 'What lesson does this teach?' using 2 picture-supported choices.","Students pick the best lesson choice and share why."], scaffolds:"Syllable pattern cards; lesson choices shown as pictures; sentence frame 'The lesson is ___'", monitor:"Syllable split accuracy (3/4); reasonable lesson choice with 1 prompt or less", notes:"Good lead-in to the whole-class fable/moral discussion" },
      on:{ id:"U5W5-O", skill:"Inferring theme; evaluating details; imagery and precise verbs", fp:"N-O", lex:"520-650L", wida:"3-5", format:"Pull-Out", size:"3-5", dur:20, materials:"Class copy/excerpt of from Aesop's Fox (anchor text), theme organizer, precise-verb highlighter sheet", proc:["Revisit the fable already read whole-class; identify 1-2 imagery-rich phrases with the group.","Model replacing a plain verb with a more precise one from the text and discussing the effect.","Students find a second precise verb with a partner.","Discuss what lesson (theme) the fable teaches and evaluate which detail best supports it.","Write 1 sentence stating the theme with the strongest supporting detail."], scaffolds:"Sentence frame 'The theme is ___. The strongest detail is ___ because ___'; partner talk before independent write", monitor:"Theme statement checked for the most relevant supporting detail, not just any detail", notes:"Directly reinforces 'Infer Theme / Evaluate Details' objective" }
    },
    { w:6, genre:"Project-Based Inquiry", text:"Take a Trip!", author:"", wq:"How does the world challenge us? (unit synthesis / research project)", comp:"Conduct Research: Bookmarking; Refine Research: Works Cited Page", vocab:"Use Academic Words", word:"Review: Vowel Patterns / Suffixes", craft:"Explore and Plan Argumentative Writing", belowRes:"Leveled Research Articles: \"Living on a Fault Line\", \"The City I Love\", \"A Mighty Flood\"",
      below:{ id:"U5W6-B", skill:"Reading a research article for key facts", fp:"K-M", lex:"350-480L", wida:"1-3", format:"Pull-Out", size:"2-4", dur:20, materials:"myView leveled research article \"The City I Love\" (or \"A Mighty Flood\"), fact-finder sticky notes", proc:["Preview the article's title and photos; predict the topic.","Read aloud in short chunks, marking one key fact per chunk with a sticky note.","Students choose their favorite fact and tell why, using a sentence frame.","Sort 3-4 facts into simple categories (e.g., 'about the place' / 'about the event').","Share one fact aloud with the group."], scaffolds:"Picture walk before reading; sentence frame 'One fact I learned is ___'; sorting mat with icons", monitor:"Teacher checklist: identifies 1 clear, accurate fact from the article", notes:"Feeds directly into the whole-class Week 6 'Take a Trip!' project" },
      on:{ id:"U5W6-O", skill:"Bookmarking sources; building a works cited page", fp:"N-P", lex:"560-780L", wida:"3-5", format:"Push-In", size:"3-6", dur:25, materials:"myView leveled research articles (\"Living on a Fault Line\", \"A Mighty Flood\"), source-citation card, note-taking organizer", proc:["Review what a works-cited entry needs (title, author/organization) with 1 example.","Students skim an article with a partner and record its citation information.","Model taking 2 notes in their own words from a source.","Partners take 2 notes of their own from a second article, citing the source.","Share one note aloud and discuss how it could support the class travel brochure project."], scaffolds:"Note-taking sentence starters ('One reason ___', 'This source says ___'); partner talk before independent note-taking", monitor:"Note-taking organizer checked for 2 accurate notes with sources correctly cited", notes:"Directly supports the whole-class Week 6 argumentative travel brochure project" }
    }
  ]
});
